- name: app-setup
  import_role:
    name: common
    tasks_from: app-setup

- name: MAVEN INSTALLATION
  import_role:
    name: common
    tasks_from: java

- name: SYSTEM SERVICE
  import_role:
    name: common
    tasks_from: systemd

- name: MYSQl SET-UP
  import_role:
    name: common
    tasks_from: mysql-setup    
