- name: Copy Mongo Repo File
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB
  dnf:
    name: mongodb-org
    state: present

- name: Start and enable MongoDB service
  systemd:
    state: started
    name: mongod
    enabled: yes

- name: Update listen address from 127.0.0.1 to 0.0.0.0
  replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restart MongoDB
  service:
    name: mongod
    state: restarted

- name: Execute netstat command
  command: netstat -tuln
  register: netstat_output

- name: Display netstat output
  debug:
    msg: "{{ netstat_output.stdout_lines }}"
