- name: DISABLING NODE.JS MODULE
  shell: "{{item}}"
  loop:
    - dnf module disable nodejs -y
    - dnf module enable nodejs:18 -y
    - dnf install nodejs -y

- name: CONFIGURE APPLICATION USER
  user:
    name: roboshop

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /app
    state: absent

- name: CREATE APP DIRECTORY
  file:
    path: /app
    state: directory

- name: DOWNLOAD APPLICATION CODE INTO APP DIRECTORY
  get_url:
    url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
    dest: /tmp

- name: UNZIP APP CODE
  unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes

- name: INSTALL NPM DEPENDENCIES
  shell: npm install
  args:
    chdir: /app

- name: COPY CATALOGUE SERVICE FILE
  copy:
    src: /home/centos/Anisible-Roboshop-Application/{{ COMPONENT }}.service
    dest: /etc/systemd/system/{{ COMPONENT }}.service

- name: RELOAD SYSTEMD DAEMON
  ansible.builtin.systemd:
    daemon_reexec: yes

- name: START CATALOGUE SERVICE
  ansible.builtin.systemd:
    name: "{{ COMPONENT }}"
    state: started

- name: COPY MONGO REPO FILE
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: INSTALL MONGODB SHELL
  dnf:
    name: mongodb-org-shell
    state: present

- name: VERIFY PRODUCTS COUNT
  command: mongo --host mongo.gonepudirobot.online --quiet --eval 'db = db.getSiblingDB("{{ COMPONENT }}"); db.products.count()'
  register: product_count

- name: PRINT PRODUCT COUNT
  debug:
    msg: "Product Count: {{ product_count.stdout }}"

- name: LOAD DATA INTO MONGODB
  shell: mongo --host mongo.gonepudirobot.online < /app/schema/{{ COMPONENT }}.js
  when: product_count.stdout == "0"

- name: RESTART CATALOGUE SERVICE
  systemd:
    name: "{{ COMPONENT }}"
    state: restarted