- name: NODE JS tasks
  import_role:
    name: common
    tasks_from: node

- name: app-setup
  import_role:
    name: common
    tasks_from: app-setup

- name: SYSTEM STARTED SERVICES
  import_role:
    name: common
    tasks_from: systemd

- name: MONOGO TASKS
  import_role:
    - name: common
      tasks_from: mongod    
