- name: NODE JS tasks
  import_roles:
    name: common
    tasks_from: nodejs

- name: app-setup
  import_roles:
    name: common
    tasks_from: app-setup

- name: SYSTEM STARTED SERVICES
  import_roles:
    name: common
    tasks_from: systemd
    
- name: COPY MONGO REPO FILE
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: INSTALL MONGODB SHELL
  dnf:
    name: mongodb-org-shell
    state: present

- name: VERIFY PRODUCTS COUNT
  command: mongo --host mongo.gonepudirobot.online --quiet --eval 'db = db.getSiblingDB("{{ COMPONENT }}"); db.products.count()'
  register: product_count

- name: PRINT PRODUCT COUNT
  debug:
    msg: "Product Count: {{ product_count.stdout }}"

- name: LOAD DATA INTO MONGODB
  shell: mongo --host mongo.gonepudirobot.online < /app/schema/{{ COMPONENT }}.js
  when: product_count.stdout == "0"

