- name: DISABLING NODE.JS MODULE
  shell: "{{item}}"
  loop:
    - dnf module disable nodejs -y
    - dnf module enable nodejs:18 -y
    - dnf install nodejs -y

- name: NPM INSTALL
  shell: npm install
  args:
    chdir: /app
