- name: COPY {{COMPONENT}} SERVICE FILE
  copy:
    src: "{{ COMPONENT }}.service"
    dest: /etc/systemd/system/{{ COMPONENT }}.service
  notify: "{{COMPONENT}}-updated" 

- name: START {{COMPONENT}} SERVICE
  ansible.builtin.systemd:
    name: "{{ COMPONENT }}"
    state: started

  